### ISSUE TITLE
What about proxy support?

### ISSUE THREAD

**Issue by FeeeeK** [FujiMakoto/pysaucenao#10]
I already have [this](https://github.com/FeeeeK/pysaucenao/tree/proxy), what do you think of that?

**Comment by FujiMakoto** [comment]
Hi @FeeeeK !

I needed to confirm with the maintainer of SauceNao that he would be okay with us implementing proxy support into the library, as there is naturally a potential for API abuse with such functionality.

He gave the go-ahead on your request and I'll be happy to review it if you can submit a pull request again.

**Comment by FeeeeK** [comment]
👍
