### ISSUE TITLE
author_name may be a list of author names for a manga source

### ISSUE THREAD

**Issue by thesadru** [FujiMakoto/pysaucenao#16]
I happened to search for [this uruha rushia image](https://user-images.githubusercontent.com/58166507/154863753-4da4d493-e0af-4314-b3c3-200a6f9292c6.jpg) which yielded:
```py
{
    "source": "SEISON&#039;T",
    "creator": [
        "butterfly"
    ],
    "eng_name": "(C99) [butterfly (Nabi)] SEISON&#039;T (Virtual YouTuber)",
    "jp_name": "(C99) [butterfly (なび)] SEISON&#039;T (バーチャルYouTuber)"
}
```

**Comment by Myned** [comment]
The `author_name` attribute accounts for this by returning only the first creator in that list:
https://github.com/FujiMakoto/pysaucenao/blob/3c6ac752413491a359b7948bc55abf4efe936519/pysaucenao/containers.py#L290-L292
If you need the complete list, then a change is required, either through a pull request, forking, or overriding the methods yourself. In my opinion, the best way to handle this is by parsing the list into a delimited string, such as:
```
self.author_name = ', '.join(data['creator'])
```
If this works for you, I've implemented it in my [fork](https://github.com/Myned/pysaucenao). I plan on eventually submitting a pull request with the fixes from there.

**Comment by thesadru** [comment]
The problem is with the manga source specifically. `author_name` gets set again but this time without any validation.

**Comment by Myned** [comment]
Understood, I can see that now. I can copy the same fix from `GenericSource` (parsing the list as a comma-delimited string), if that works for you.

**Comment by thesadru** [comment]
Yeah, that's fine. I was just surprised by it being a list since the annotation said it would always be an optional str.

**Comment by FujiMakoto** [comment]
> Yeah, that's fine. I was just surprised by it being a list since the annotation said it would always be an optional str.

It actually should always be either a string or None, if it's returning a list here I'd consider that a bug.

I'd rather not change it to return a preformated comma-separated list. What about adding an `authors` attribute that is always a list instead here? This would contain all authors if there are multiple, or a list of just one author if there is one.

But as for author_name returning a list here, that is a bug and I'll have a fix submitted for that.
