### ISSUE TITLE
Anime sources should be prioritized when meeting a minimum similarity threshold

### ISSUE THREAD

**Issue by FujiMakoto** [FujiMakoto/pysaucenao#5]
People on Deviantart and so on like to post gifs from their favorite anime's, which SauceNao picks up and indexes.

The problem with this is, it can lead to these reposts being prioritized over the actual anime sources, which we don't want happening.

Example:
https://twitter.com/saucenaopls/status/1274274631042678786

A filter should be added to make sure anime sources are displayed first when they meet a minimum similarity threshold (of let's say 80 or so)

**Comment by FujiMakoto** [comment]
Additionally we should probably consider adding a flag to disable this behavior in __init__. Something like `priority_mode = True` or so.

**Comment by FujiMakoto** [comment]
Reconsidering whether we should actually do this in this library or leave it to the applications using this logic to handle this.

**Comment by FeeeeK** [comment]
Maybe make priority settings by source indices?  something like `priority = [6, 5]` 
Then index 6 in the results will be the first and 5 the second

**Comment by FujiMakoto** [comment]
@FeeeeK Yeah I was thinking of doing something just like that.

My hesitation is when doing this, you probably want to balance similarity in there too.

So, if you have something that's a 90% match on Pixiv for example, but has a 55% match on Anime, you probably don't want to prioritize the anime result due to the vastly lower similarity rating.

Could maybe add another argument to handle the maximum percentage difference to accept when prioritizing results (e.g. only prioritize anime results if it's within 10% similarity of the highest rated result).

I think that would work actually. Just need to figure out a good name for that paremeter that easily conveys what it does, lol.
