### ISSUE TITLE
SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by CalebThePerson** [FujiMakoto/pysaucenao#7]
When I run the code

>from pysaucenao import SauceNao, PixivSource
sauce = SauceNao()
results = await sauce.from_url('https://i.imgur.com/oVPWy7f.png') 

I get the error of ,  I made sure to install pysaucenao along with aiohttp just in case and I keep getting this weird message.  Sorry if it's obvious fix or mentioned the solution elsewhere
>SyntaxError: 'await' outside function

**Comment by FujiMakoto** [comment]
pysaucenao is an asynchronous library, so you'll need to call the code in an event loop of some sort.

If you just want to test, this is one way to do it:
```python
from pysaucenao.saucenao import SauceNao
import asyncio

loop = asyncio.get_event_loop()

sauce= SauceNao()
results = loop.run_until_complete(sauce.from_url('https://i.imgur.com/oVPWy7f.png'))
```

But mainly this is meant to be used in asynchronous applications, such as Discord bots and so on. So in reality, you'd be using it in async functions,

```python
from pysaucenao.saucenao import SauceNao
import asyncio


async def main():
    sn = SauceNao()
    return await sn.from_url('https://i.imgur.com/oVPWy7f.png')

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    r = loop.run_until_complete(main())
```
